DROP TABLE IF EXISTS sewers CASCADE;
DROP TABLE IF EXISTS sewermonsters;


CREATE TABLE sewers(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
size TEXT,
smelly_scale TEXT
);



CREATE TABLE sewermonsters(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
type TEXT NOT NULL,
cute TEXT,
ferocious TEXT,
sewers_id BIGINT REFERENCES sewers(id)
);


